### ISSUE TITLE
openai library error

### ISSUE THREAD

**Issue by maiphong0411** [AndrewNgo-ini/agentic_rag#1]
I have installed as requirements.txt and I got an error about openai library

<img width="531" alt="image" src="https://github.com/user-attachments/assets/be43f1da-670c-4c8d-9d6c-443b2c3908d8">

I upgrade openai==1.55.3, it works

**Comment by maiphong0411** [comment]
Full log for the error
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/d255c274-dc85-4163-a8b6-0c3698b32b5c">

**Comment by AndrewNgo-ini** [comment]
@maiphong0411 thank you so much, i got the same problem but forgot to update in requirements.txt, I've made a commit to update it. Appriciate
